version: '3'
services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        restart: always
        volumes:
            - ./mongo:/data/db
    backend:
        image: makaarim/to-do-backend
        ports:
            - "8080:8080"
        environment:
            DB_URI: mongodb://root:example@mongo:27017/test?authSource=admin
            DB_NAME: test
            DB_COLLECTION_NAME: todolist
        restart: always
        depends_on:
            - mongo
    frontend:
        image: makaarim/to-do-frontend
        ports:
            - "3000:3000"
        restart: always
